version: '3'
services:
  api:
    container_name: api1.0
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes: 
      - './mongodbdata:/data/db'

#sudo docker-compose up